### PR TITLE
Choice of Hash Function

### PR DESCRIPTION
**Pull request by philcockfield**
Issue: #23 

```ts
const cache1 = new FileSystemCache();                    // ← default: "sha1"
const cache2 = new FileSystemCache({ hash: 'sha256' });
const cache3 = new FileSystemCache({ hash: 'sha512' });
```

### CODE REVIEW

**Comment by philcockfield** [comment]
@trevor-vaughan I've added a `sha256` option...any other algorithms you'd like to see added as options?

**Comment by trevor-vaughan** [comment]
@philcockfield Ideally, you'd pull the available hashes out of the underlying installation and allow for any from that list.

```javascript
crypto = require('crypto')
hashes = crypto.getHashes()
```

**Comment by philcockfield** [comment]
that's better @trevor-vaughan - cheers!

**Comment by philcockfield** [comment]
Published as [2.4.0](https://www.npmjs.com/package/file-system-cache/v/2.4.0)

**Pull request merged**
