### PR TITLE
Revive this outdated repository

### PR DESCRIPTION
**Pull request by nopeless**
Updated test specs, removed useless babel plugins

It also exports the class by default instead of exporting a function that returns a new instance (??????????? why????)

### CODE REVIEW

**Comment by nopeless** [comment]
oops i rebased too much

**Review by ndelangen — APPROVED** [review]

**Comment by nopeless** [comment]
the last two commits were added due to an issue with using github repo as npm package

**Comment by nopeless** [comment]
I will no longer maintain my fork.

If you want to use a better cache -> https://github.com/nopeless/nope-fs-cache

You can close this issue if you want

**Comment by philcockfield** [comment]
cheers @nopeless

**Pull request closed without merging**
